[package]
name = "csv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
csv = "1"
fallible-iterator = "0.3"
quirky_binder_support = { path = "../../quirky_binder_support" }
serde = "1"
static_assertions = "1"
truc_runtime = "0.3"

# quirky_binder_monitor
chrono = { version = "0.4", optional = true }
self-meter = { version = "0.6", optional = true }
tracking-allocator = { version = "0.4", optional = true }

[features]
default = []
quirky_binder_monitor = ["chrono", "self-meter", "tracking-allocator"]

[build-dependencies]
quirky_binder = { path = "../../quirky_binder" }
quirky_binder_csv = { path = "../../contrib/quirky_binder_csv" }
truc = "0.3"
