name: Continuous Integration

on:
  workflow_dispatch:
  push:

jobs:

  main_stable:
    name: Rust stable
    uses: ./.github/workflows/_build.yml
    with:
      rust_toolchain: stable
      with_rustfmt: true

  main_1_65_0:
    name: Rust 1.65.0
    uses: ./.github/workflows/_build.yml
    with:
      rust_toolchain: 1.65.0
      with_clippy: true
      pre_build_script: ./scripts/msrv_pin_dependencies.sh

  main_nightly:
    name: Rust nightly
    uses: ./.github/workflows/_build.yml
    with:
      rust_toolchain: nightly

